# Generated by Django 4.0.5 on 2022-06-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_skill_skill_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_facebook',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_instagram',
            new_name='social_twitter',
        ),
    ]
