# Generated by Django 4.0.4 on 2022-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='down_vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('dw', 'Down Vote')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='up_vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('dw', 'Down Vote')], max_length=2, null=True),
        ),
    ]
