# Generated by Django 4.0.5 on 2022-06-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_social_facebook_profile_social_linkedin_and_more'),
        ('project', '0003_alter_review_down_vote_alter_review_up_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
